pytests_initial_hw_commit
DanTheMain/testing_exercises pull request #1
Opened 2023-09-07 14:12 UTC by DanTheMain

2023-09-09 07:02 UTC, vppuzakov requested changes
👍 найдено по несколько кейсов на каждую из тестируемых функций.
💡 на каждый кейс давай сделаем отдельный тест с обязательным отражением в названии тестируемого поведения

2023-09-09 07:02 UTC, vppuzakov commented on tests/level_1/test_one_gender.py
> +    verb_male, verb_female = 'verb_male', 'verb_female'
👍 найдены разные тестовые кейсы
💡 разные тест кейсы точно стоит вынести в разные тесты и отразить эти кейсы / ожидаемое поведение в названии теста по следующему шаблону.

`test__genderalize__do_something`

2023-09-09 07:02 UTC, vppuzakov commented on tests/level_1/test_one_gender.py
> +    assert (verb_male == genderalize(verb_male, '', 'male'))
💡 assert пишем без скобок, и если у нас oneliner - то вот так

```python
assert genderalize(verb_male, '', 'male') == verb_male
```

Во всех тестах это давай поправим

2023-09-09 07:02 UTC, vppuzakov commented on tests/level_1/test_two_date_parser.py
>  def test_compose_datetime_from():
👍 найдены хорошие кейсы, покрывающие все пути исполнения тестируемой функции
💡 но именно поэтому это сложный тест, так как кейсы разные - то и тестов должно быть по одному на каждый кейс с обязательным заданием кейса / ожидаемого поведения в названии

2023-09-09 07:02 UTC, vppuzakov commented on tests/level_1/test_two_date_parser.py
> +    test_time_str = f'{test_hours}:{test_minutes}'
💡 формирование строки со временем можно вынести в фикстуру (не сейчас) - пока давай тест разобьем на несколько по кейсам и упростим и потом посмотрим, нужна ли нам будет такая фикстура

2023-09-09 07:02 UTC, vppuzakov commented on tests/level_1/test_two_date_parser.py
> +    assert (expected_datetime_today == compose_datetime_from("someday today", test_time_str))
💡 в зависимости от тестируемого кейса не обязательно сравнивать дату один в один, можно например сравнить, что день / месяц / год заданы верно - возможно в этом ассерте мы смотрим что должна вернуться дата за сегодня.

В другом кейсе за завтра, в другом - что часы минуты корректно парсятся

2023-09-09 07:02 UTC, vppuzakov commented on tests/level_1/test_three_url_builder.py
>  def test_build_url():
👍 кейсы нашел хорошие
💡 тестируем разные кейсы - давай вынесем в разные тесты (обязательно в названии отразить кейс)

2023-09-09 07:02 UTC, vppuzakov commented on tests/level_1/test_four_bank_parser.py
> +from typing import NamedTuple
💡 неиспользуемый импорт

2023-09-09 07:02 UTC, vppuzakov commented on tests/level_1/test_four_bank_parser.py
> +    expected_expense = Expense(
💡 из этого теста если сильно не вглядываясь - непонятно какой именно кейс тестируем. По хорошему надо этот кейс отразить в названии теста.

💡 Стоит поискать еще кейсов для тестов этой функции.

💡 если будет понятен кейс, то нет необходимости создавать expense чтобы сравнить на полное соответствие, согласно кейсу можно проверять только те поля что проверяем в кейсе. Например, в кейсе "сумма платежа распарсилась" можно проверять только decimal сумму:

```python
expense = parse_ineco_expense(sms, cards)
assert expense.amount == decimal.Decimal('12.34')
```

2023-09-09 07:02 UTC, vppuzakov commented on tests/level_1/test_five_title.py
>  def test_change_copy_item():
👍 найдено много кейсов
💡 сложно понять каких - поэтому давай вынесем в разные тесты и отразим тестируемые кейсы в названии

2023-09-11 10:42 UTC, DanTheMain commented on tests/level_1/test_one_gender.py
> +    verb_male, verb_female = 'verb_male', 'verb_female'
Done

2023-09-11 10:44 UTC, DanTheMain commented on tests/level_1/test_two_date_parser.py
> +    test_time_str = f'{test_hours}:{test_minutes}'
разбил. Форматирование строки пока оставил

2023-09-11 10:45 UTC, DanTheMain commented
> 👍 найдено по несколько кейсов на каждую из тестируемых функций. 💡 на каждый кейс давай сделаем отдельный тест с обязательным отражением в названии тестируемого поведения

Done

2023-09-11 10:45 UTC, DanTheMain commented on tests/level_1/test_five_title.py
>  def test_change_copy_item():
вынес тесты в разные кейсы с названиями

2023-09-11 10:46 UTC, DanTheMain commented on tests/level_1/test_four_bank_parser.py
> +    expected_expense = Expense(
разбил на проверки базовых характеристик в кейсах.

2023-09-11 10:47 UTC, DanTheMain commented on tests/level_1/test_four_bank_parser.py
> +from typing import NamedTuple
удалил

2023-09-11 10:47 UTC, DanTheMain commented on tests/level_1/test_three_url_builder.py
>  def test_build_url():
вынес в разные кейсы

2023-09-11 10:53 UTC, DanTheMain commented on tests/level_1/test_two_date_parser.py
> +    assert (expected_datetime_today == compose_datetime_from("someday today", test_time_str))
разбил на 2 кейса. Надо ли добавить кейс про парсинг  часов и минут?

2023-09-11 10:53 UTC, DanTheMain commented on tests/level_1/test_one_gender.py
> +    assert (verb_male == genderalize(verb_male, '', 'male'))
Done

2023-09-15 14:10 UTC, vppuzakov approved these changes
👍 в рамках первой недели шикарно, найдены хорошие кейсы
👍 и очень круто, что разбиты тесты по найденным кейсам
💡 поработай еще над названиями тестов (обязательно ожидаемое поведение)

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_one_gender.py
> +def test_male_genderalization():
💡 используй такой шаблон при именовании тестов:

`test__funcname__case_and_bahaviour`

- funcname - тестируемая функция
- case_and_behaviour - кейс / ожидаемое поведение

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_one_gender.py
> +    assert verb_male == genderalize(verb_male, '', 'male')
💡 будем читаемей, если перевернуть `genderalize(verb_male, ...) == verb_male`

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_one_gender.py
> +    verb_male = 'verb_male'
💡 по-идее, можно обойтись без установочной переменной и воспользоваться `oneliner` - так как тест простой и так будет еще проще его читать:

```python
assert genderalize('verb_male', '', 'male') == 'verb_male'
```

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_one_gender.py
> +def test_matching_male_genderalization():
💡 вот тут отстутствие ожидаемого поведения в названии теста не позволяет мне понять, возможно, данный кейс лишний. Всегда указывай ожидаемого поведение в названии теста.

Судя, по телу теста, здесь тестируем, что для male надо вернуть не female verb. Ну как будто название такое надо дать:

`test__genderalize__not_return_female_verb_for_male_gender` и стало бы сразу понятнее и читать эти тесты и интерпретировать ошибки по ним в логах сборки.

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_one_gender.py
> +    assert (verb_female != genderalize(verb_male, '', male_gender))
💡 весь тест также можно сделать oneliner, смотри насколько проще и яснее они станут:

```python
 assert genderalize('verb_male', 'verb_female', 'male') != 'verb_female'
```

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_two_date_parser.py
> +def test_compose_datetime_from_tomorrow():
👍 отразил в названии тестируемую функцию
💡 только раздели ее двойным подчеркиванием `test__funcname__case_behaviour`
💡 добавить ожидаемое поведение - какой-то глагол что-ли - вроде:

`test__compose_datetime__return_next_day_for_tomorrow`

Это полезно, так как облегчает восприятие тестов и в коде и по логам запуска pytest

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_two_date_parser.py
> +    assert expected_datetime_today == compose_datetime_from("someday today", test_time_str)
💡 не обязательно сравнивать сразу с полной интерпретацией даты - в зависимости от того, что тестируется. Обязательно указывай не только вход, но и ожидаемое поведение, тогда и тест будет проще:

```python
def test__...__return_current_day_when_tomorrow_not_passed():
    # благодаря тому, что в тесте мы проверяем только день, а не все сразу - сам тест станет проще
    today = datetime.datetime.now()
 
    dt = compose_datetime_from(...)

    assert dt.date() == today.date()
```

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_two_date_parser.py
> +    test_hours, test_minutes = random.choice(range(1, 24)), random.choice(range(10, 60))
💡 рандомные значения использовать можно безопасно, когда они не оказывают влияния на тест и не используются в ассерте. 

Иначе, есть вероятность получить мигающий тест, когда от запуска к запуска он либо работает, либо нет. 

Эту проблему несколько решает [hypothesis](https://hypothesis.readthedocs.io/en/latest/), он за один тест запускает диапазон проверок, на основании спецификации доступных значений. То есть тест сфейлит гораздо чаще от запуска к запуску и мигания не допустим.

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_two_date_parser.py
> +    test_time_str = f'{test_hours}:{test_minutes}'
💡 давай потом найдем еще кейсов именно на время и напишем тесты на это. Например, что если передать время в формате `12:00pm`

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_three_url_builder.py
> +def test_build_url_with_params():
💡 раздели тестируемую функцию и кейс двойным подчеркиванием: `test__build_url__case`
💡 смотрю на этот тест и на `params_order_matters` и они один в один похожи, причем второй мне нравится больше - там ожидаемого поведение отражено в названии, а этот тест давай удалим

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_three_url_builder.py
> +    host_name, rel_url, params = 'test_host', 'test_url', {'p1': 'pararam', 'p2': 'pam-pam'}
💡 если можно сделать тест проще - то можно использовать oneliner, тест должен быть простым и понятным, переменные его только усложняют

```python
   assert build_url('host', 'path', {'p1': 'first', 'p2': 'second'}) == 'host/path?p1=first&p2=second'
```

не всегда можно обойтись конечно без установочных переменных - но когда можно - давай не переусложнять заранее

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_three_url_builder.py
> +def test_build_url_no_params():
💡 название теста может быть длинным, лишь бы было читаемым, понятным и содержало кейс и ожидаемое поведение - вроде:

`test__build_url__without_params_not_include_params_delimiter`

читается как есть:

`проверяем, что наша функция build_url без параметров не содержит ? разделитель`

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_three_url_builder.py
> +    assert f'not a host/{rel_url}' != build_url(host_name, rel_url)
💡 тут бы лучше зашла проверка по переданному `hostname`:
```python
assert build_url('test_host', 'test_url').startswith('test_host')
```

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_four_bank_parser.py
> +    assert isinstance(parse_ineco_expense(SmsMessage(
💡 слишком суровый `oneliner`, настолько суровый, что не сразу заметил, что мы тут isinstance чекаем :)

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_four_bank_parser.py
> +    assert isinstance(parse_ineco_expense(SmsMessage(
🔴 очень в редких кейсах нужно проверять, инстанс какого типа нам возвращается. 

В данном случае, функция всегда возвращает `Expense`, дальше лучше доверить дело аннотациям типов и запускать `mypy` - тестировать надо только логику.

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_four_bank_parser.py
> +def test_ineco_expense_card_choice():
💡 давай писать полное название функции - `parse_ineco_expense`, потом удобно искать тесты на определенную функцию, если использовать ее полное название

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_four_bank_parser.py
> +    expected_last_digits, expected_owner_name = '1234', 'matching_card_owner_1'
👍 тут установочная часть теста весьма кстати

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_four_bank_parser.py
> +                  BankCard(last_digits=f'{expected_last_digits}', owner='non_matching_card_owner_2')]
💡 видно, что тестируется, что у нас на входе две карты с одинаковыми последними цифрами. Стоит это отразить в названии теста, либо убрать эту деталь отсюда, если мы никак не проверяем этот момент в проверках (но кейс хороший - достоен еще одного теста)

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_four_bank_parser.py
> +    actual_test_card = parse_ineco_expense(test_sms, test_cards).card
💡 лучше сложить как есть то, что мы получаем на вызове функции

```python
    expense = parse_ineco_expense(test_sms, test_cards)
```

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_four_bank_parser.py
> +    assert(actual_test_card.last_digits == expected_last_digits and actual_test_card.owner == expected_owner_name)
🔴 не надо объединять проверки таком образом, гораздо читаемее и понятнее в том числе в логах в случае ошибки будет разнести на два ассерта:

```python
    assert expense.card.last_digits == expected_last_digits
    assert expense.card.owner == expected_owner_name
```

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_four_bank_parser.py
> +def test_ineco_expense_amount():
👍 классно, что тестируешь отдельные аспекты поведения функции и проверки делаешь на часть expense, в данном случае `amount`
💡 не хватает какого то глагола за ожидаемое поведение - не экономь - на длину названия теста ограничения нет - лишь бы был понятный, вроде `return_correct_amount`

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_four_bank_parser.py
> +    expected_test_amount = decimal.Decimal(f"{test_amount_str}")
💡 f-string лишняя

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_four_bank_parser.py
> +    test_amount_str = "12.34"
💡 лучше обойтись без двух переменных, например:
`amount = Decimal('12.34')`, `Decimal` также в строку красиво преобразуется

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_four_bank_parser.py
> +    assert (parse_ineco_expense(SmsMessage(
💡 у нас уже не `oneliner`, поэтому давай лучше разобьем на arrange, act, assert части теста - иначе ниче не понятно что там внутри намешано.

```python
sms = ...
cards = [...]

expense = parse_ineco_expense(sms, cards)

assert expense.amount == amount 
``` 

В двух следующих тестах такие же комменты

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_five_title.py
> +    assert (title_over_max == change_copy_item(title_over_max, max_title_length)), \
💡 комментарий к ассерту лучше как раз отразить в названии теста - только не в виде фейла, а в виде того, что же мы ожидаем от этого теста

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_five_title.py
> +    title_over_max = f"{'a'.join(['a' * max_title_length])}"
💡 тут может пригодится фикстура-фабрика в дальнейшем

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_five_title.py
> +    assert (f'{additional_copy_text} {sample_title}' == change_copy_item(sample_title))
💡 только вывернуть проверку `assert change_copy_item(...) == ...`

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_five_title.py
> +    assert (default_title_over_max == change_copy_item(default_title_over_max)), \
💡 убрать коммент к ассерту в качестве ожидаемого поведения в название теста

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_five_title.py
> +def test_title_starting_with_copy_of_text_with_copy_number():
💡 название теста обязательно должно включать в себя название тестируемой функции по шаблону: `test__funcname__case_and_behaviour`

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_five_title.py
> +    assert (f'{additional_copy_text} {sample_title}' == change_copy_item(sample_title))
💡 кажется, было бы проще завернуть в oneliner
```python
assert change_copy_item('sample') == 'Copy of sample'
```

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_five_title.py
> +    assert (f'{additional_copy_text} (2)' == change_copy_item(additional_copy_text))
💡 `oneliner` был бы проще

2023-09-15 14:10 UTC, vppuzakov commented on tests/level_1/test_five_title.py
> +    assert (f'{additional_copy_text} {sample_title} ({sample_copy_number + 1})' == change_copy_item(
💡 тест получился как будто более сложный чем сама тестируемая фукнция, сравни такой вариант:

```python
def test__...__():
    assert change_copy_item('Copy of title') == 'Copy of title (1)'
```

не переусложняй тест, кто затестит потом сам наш тест, если в нем будет много кода - верно?

2023-09-15 14:39 UTC, DanTheMain commented on tests/level_1/test_one_gender.py
> +    assert (verb_female != genderalize(verb_male, '', male_gender))
> 💡 весь тест также можно сделать oneliner, смотри насколько проще и яснее они станут:
> 
> ```python
>  assert genderalize('verb_male', 'verb_female', 'male') != 'verb_female'
> ```

согласен, с переменными тут только из за моей лени печатать строчки и копипасты. Было бы наверное удобней передавать тестовые данные параметрами или через декораторы, но мы пока этого не изучали )

2023-09-15 14:42 UTC, merged